site_name: Java 21 Study Guide
site_url: https://ars-digitale.github.io/java-21-study-guide/
repo_url: https://github.com/Ars-Digitale/java-21-study-guide
repo_name: Ars-Digitale/java-21-study-guide

docs_dir: docs
site_dir: site

theme:
  name: material
  language: en

plugins:
  - search

nav:
  - Home: index.md
  - English: en/index.md
  - Italiano: it/index.md
  - FranÃ§ais: fr/index.md
